import React from "react";
import Image from "next/image";
import { DocsThemeConfig } from "nextra-theme-docs";
import Link from "next/link";

const products = [
  {
    name: "ViveReports",
    path: "/vive-reports",
    description: "ViveReports: Track Video Performance",
  },
  {
    name: "Vive API Suite",
    path: "/vive-api-suite",
    description: "API documentation",
  },
];

// Define the ProductsDropdown component
const ProductsDropdown = () => {
  // Basic styling for the dropdown, you'll likely want to enhance this in your CSS
  // Or use a headless UI library for a more robust dropdown.
  return (
    <div className="nx-relative group">
      {" "}
      {/* Use Nextra's utility classes or your own */}
      <button className="nx-p-2 nx-text-sm nx-font-medium">Products ▾</button>
      <ul className="nx-absolute nx-right-0 nx-z-20 nx-mt-1 nx-hidden group-hover:nx-block nx-bg-white dark:nx-bg-neutral-800 nx-border nx-border-gray-200 dark:nx-border-neutral-700 nx-rounded-md nx-shadow-lg nx-py-1">
        {products.map((product) => (
          <li key={product.path}>
            <Link
              href={product.path}
              className="nx-block nx-px-4 nx-py-2 nx-text-sm nx-text-gray-700 hover:nx-bg-gray-100 dark:nx-text-gray-200 dark:hover:nx-bg-neutral-700"
            >
              {product.name}
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
};

const config: DocsThemeConfig = {
  logo: (
    <span className="nx-flex nx-items-center nx-gap-2">
      <Image src="/logo.svg" alt="vive-docs-logo" width={24} height={24} />
      <span>ViveDocs</span>
    </span>
  ),
  project: {
    link: "https://github.com/ViveScriptSolutions/doc-vs",
  },
  logoLink: "/",
  chat: {
    link: "https://discord.com",
  },
  docsRepositoryBase: "https://github.com/ViveScriptSolutions/doc-vs",
  useNextSeoProps() {
    // Sensible defaults for SEO
    return {
      titleTemplate: "%s – ViveDocs",
    };
  },
  // Configure the top navigation.
  // Items like "Home", "About", "Contact" will typically be generated by Nextra
  // potentially ordered by a `pages/_meta.json`.
  // The `navbar.items` here are for *additional* items or structured menus.
  navbar: {
    extraContent: <ProductsDropdown />,
  },
  footer: {
    text: `© ${new Date().getFullYear()} ViveScript Solutions. All rights reserved.`,
  },
  sidebar: {
    defaultMenuCollapseLevel: 1, // How many levels to expand by default
    toggleButton: true,
  },
  // editLink: {
  //   text: "Edit this page on GitHub →",
  // },
};

export default config;
